### ISSUE TITLE
OIDAuthState.authState fails to show browser on iOS 13

### ISSUE THREAD

**Issue by taimila** [openid/AppAuth-iOS#400]
**Describe the bug**
When built with 11.0 beta (11M336w) for iOS 13 beta 1, `OIDAuthState.authState(byPresenting: request, presenting: parentController)` returns the following error:

`Error Domain=org.openid.appauth.general Code=-3 "(null)" UserInfo={NSUnderlyingError=0x6000034351d0 {Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}}}`

**Expected behavior**
Show identity provider's authentication page.

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13 Beta 1

**Additional context**
API has worked as expected with previous versions. I'm not sure is there something to be updated in AppAuth library or is there a bug in iOS 13 Beta that causes this behaviour, but I think it's worth to investigate.

**Comment by WilliamDenniss** [comment]
AppAuth will need to be updated to support iOS 13.

**Comment by glaphi** [comment]
There might be an issue with bridging or project setup. 
Obj-c request starts as expected Xcode-beta + iOS 13 on iPhone X. 
Presentation is done differently tho.

**Comment by Schlabbi** [comment]
We installed the ios13beta branch to get the login to work again for iOS 13 but the authentication instantly fails. In our logs we can see these errors:

> [strings] ERROR: org.openid.appauth.general not found in table Error of bundle CFBundle 0x10cd09200 </System/Library/Frameworks/CoreFoundation.framework> (framework, loaded)

> Authorization error: The operation couldn’t be completed. (ORG.OPENID.APPAUTH.GENERAL error -3.)

Any input on this?

**Comment by ChristianSteffens** [comment]
Same issue here  installed latest commit of `ios13beta` - still failing

> Authorization error: The operation couldn’t be completed. (ORG.OPENID.APPAUTH.GENERAL error -3.)

**Comment by CarloMatic** [comment]
confirmed :(

**Comment by IldarAbdullin-okta** [comment]
@Schlabbi , @ChristianSteffens , @CarloMatic , what beta version you use for testing? I tested with iOS13 beta 3 and everything works fine on both simulator and device

**Comment by marvindrion** [comment]
Hello, I get the same error with iOS 13 Simulator and XCode 11.0 Beta5 : 
Authorization error: The operation couldn’t be completed. (org.openid.appauth.general error -3.)

**Comment by IldarAbdullin-okta** [comment]
Tested with iOS13 Simulator and XCode 11.0 Beta5, can't reproduce. Tested with Okta endpoint

**Comment by marvindrion** [comment]
I tested it with the new 1.1.0 version, I still get the bug. I downgraded my version to 0.95.0 and the bug disappears.

**Comment by WilliamDenniss** [comment]
Only the `ios13beta` branch has been tested with the iOS 13 beta. AppAuth doesn't officially support beta versions of iOS, so any results will be unpredictable when running official AppAuth releases on beta versions of iOS.

If you're testing the beta, point your CocoaPods or Carthage file at the AppAuth `ios13beta` branch (and let us know how you go!). 

This branch will be merged, and a new version cut when iOS 13 goes GA.

**Comment by WilliamDenniss** [comment]
This issue has been resolved in the `ios13beta` branch. Point your Podfile or Cartfile at the `ios13beta` branch to try it out.

**Comment by Schlabbi** [comment]
It is working now on iOS 13 beta 6 without any problems so far. Will write again if we notice anything weird.

**Comment by WilliamDenniss** [comment]
Thanks for the update! Glad it's working in the latest version.

It's not uncommon for iOS betas to have issues (kind of the point really), but good that everyone is testing it! Just remember to file bugs to Apple directly for any operating system bugs you encounter (if they are OS issues, as opposed to AppAuth ones), as I'm not aware of anyone there who reads the issues here.

**Comment by KlemensStrasser** [comment]
Thanks for the initial solution, great to see it working again. 
But I've ran into an issue in combination with iOS13 multi window support. The current solution takes the `keyWindow` of the `UIApplication`, but this  has been [deprecated in iOS13](https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow?language=objc). 
Just to prevent confusion: If you create multiple "windows", you actually create multiple (window)scenes, where each one can have multiple windows. 
Thus, when dealing with multiple scenes , there is no (single) keyWindow anymore. Calling `UIApplication.keyWindow` can return a UIWindow of any of scene, even from a scene that is currently in the background. To prevent this from happening, I've implemented a solution in pull request #428 where the window of a fitting scene is selected as the presentationAnchor. The fix also doesn't break anything if the app has no multi-window support, since in that case there is exactly one windowScene.

**Comment by fprosper** [comment]
Same error also using CocoaPods with iOS 13 simulator Xcode 11 beta 7 pointing to ios13beta branch

**Comment by chintu-github** [comment]
I have consumed 1.2.0 version which says iOS 13 support available. Still, I am facing this issue. I am using Xcode 11 GM seed and app auth 1.2.0. Please let me know which version to consume for ios 13 to get rid of this issue.

**Comment by ATranDev** [comment]
Same error

**Comment by amitasethi** [comment]
Still getting the same error. 
authorization error: The operation couldn’t be completed. (org.openid.appauth.general error -3.)

I am pointing to 	pod 'AppAuth', '~> 1.2.0'

**Comment by amodkanthe** [comment]
I am also getting error for pod 1.2.0 on ios 13 what to do? any fix for this?

**Comment by JoKuebler** [comment]
Same error here on my simulator running iOS 13 with version 1.2.0

**Comment by amodkanthe** [comment]
Found solution on this follow these steps
1)remove this line from pod file pod 'GoogleSignIn'
2)run command install pod
3)again add line to pod file pod 'GoogleSignIn'
4)run command pod install again
5)now try it will work fine

**Comment by JoKuebler** [comment]
I'm not using GoogleSignIn in the first place

**Comment by amodkanthe** [comment]
Try reinstalling related pod then as above steps

**Comment by dammdev** [comment]
I have the same error (Error Domain=org.openid.appauth.general Code=-3). 
Does anyone have status about the error?
 I have pod 'AppAuth', '~> 1.2.0'
